# Generated by Django 4.0.6 on 2022-07-27 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_Info',
            fields=[
                ('boolean', models.BooleanField(default=True, null=True, verbose_name='this is a boolean field')),
                ('char', models.CharField(help_text='added help text', max_length=200, null=True, unique=True, verbose_name='New name')),
                ('date', models.DateField(default=django.utils.timezone.now, null=True)),
                ('decimal', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('email', models.EmailField(max_length=200, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads')),
                ('integer', models.IntegerField(null=True)),
                ('positive_int', models.PositiveBigIntegerField(null=True)),
                ('slug', models.SlugField(blank=True)),
                ('text', models.TextField(null=True)),
                ('url', models.URLField(null=True)),
                ('uuid1', models.UUIDField(default=uuid.uuid4, null=True)),
                ('uuid2', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('created', models.DateField(auto_now_add=True, null=True)),
                ('date_and_time', models.DateTimeField(null=True)),
                ('choice', models.CharField(choices=[('one', 'number One'), ('two', 'number Two')], max_length=10, null=True)),
                ('new_field', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
